### ISSUE TITLE
Please review week 6 changes 

### ISSUE THREAD

**Issue by vrumale** [MyChallenger/Challenger#12]
Please review week 6 changes. /cc @codepathreview @codepath
![challenger_week2](https://cloud.githubusercontent.com/assets/9405213/6609721/96fdbc2a-c812-11e4-8a58-22945d774fd2.gif)

**Comment by codepathreview** [comment]
:+1: Nice work creating wire-frames and creating stories for sprint 1. Great to see the basic screens and flow coming along well. Few notes to mention:
- Consider dividing a bigger parent story/feature into a number of smaller tasks - provides a better picture of the progress on the issue.
- Group projects can reinforce skills that are relevant to both group and individual work including the ability to plan and manage time. For this reason, it is imperative that you [group all detailed issues into milestones](https://github.com/MyChallenger/Challenger/milestones) representing sprints so that its easier for you to track progress of the project.
- Consider creating group [milestones/pull requests](https://help.github.com/articles/creating-and-editing-milestones-for-issues-and-pull-requests/) to better track your progress and review each others code.
- Work load needs to be divided equally among all members of the team. This is critical in working as a team and also gives equal learning opportunity to everyone involved. Please make sure everyone is [contributing](https://github.com/MyChallenger/Challenger/graphs/contributors) to the team for next sprint.
- Consider creating tasks to complete the creation of your database schema and its respective models. Also, consider integrating with Parse if you haven't already.
- Depending on the strategy your group has come up with, consider creating regular pushes/pull-requests to sync up your code to avoid having multiple errors at the end.
- Consider creating tasks to QA the app a few times to check the basic flow. Integration testing will especially be important for this project since each team member is working on a separate module. The best part is seeing it all come together into a polished app.

Good to see the basic flow coming along well. Please take notes of these points and improve upon the same in the next sprint. Look forward to the rest of the functionality and improvement on the core flows by the end of the Sprint 2 so you can have enough time to add UI polish and advanced nice-to-have features later on.  It is those little extra things you do that make everything feel more polished and desirable to use.
